# Generated by Django 5.1.6 on 2025-03-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersupply',
            name='efficiency_rating_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
