# Generated by Django 5.1.6 on 2025-04-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_powersupply_efficiency_rating_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='bios_compatibility',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='chipset_compatibility',
            field=models.CharField(max_length=255),
        ),
    ]
