# Generated by Django 5.1.6 on 2025-04-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_powersupply_efficiency_rating_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="motherboard",
            name="supported_storage_interfaces",
            field=models.JSONField(default=list),
        ),
    ]
