# Generated by Django 5.1.6 on 2025-04-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_motherboard_supported_storage_interfaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolingaccessory',
            name='supported_sockets',
            field=models.JSONField(default=list),
        ),
    ]
