# Generated by Django 5.1.6 on 2025-04-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coolingaccessory_supported_sockets'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='supported_pcie_standards',
            field=models.JSONField(default=list),
        ),
    ]
