# Generated by Django 5.1.6 on 2025-04-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_motherboard_supported_pcie_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='computercase',
            name='supported_cooling_types',
            field=models.JSONField(default=list),
        ),
    ]
