# Generated by Django 5.1.6 on 2025-04-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_computercase_supported_cooling_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apps\\core\\static\\images\\gpu'),
        ),
    ]
